#!/usr/bin/env bash
# connect-agent.sh — wire exobrain scope content into an AI agent's surface.
#
#   connect-agent.sh <claude|codex|openclaw> [--relink] [--configure] [--render-specs-only]
#
# A scope is any directory containing an AGENTS.md. Connecting a leaf scope
# (recorded in .exobrain.json `connected_scopes`) wires in that leaf plus every
# AGENTS.md-bearing ancestor up to the repo root — resolving skills, specs, and
# the optional-skills index innermost-wins. See domains/exobrain/ for the model.
#
# Agent surfaces — each agent gets its OWN surface; no two agents ever write the
# same generated file (the composed content is agent-specific — filtered skills
# index, per-agent paths — so a shared file would let the last writer clobber it):
#   claude   → .claude/CLAUDE.md @-imports .claude/connected-scopes.md (a manifest of
#              live source specs) + .claude/optional-skills.md + .claude/tools-index.md
#   codex    → ~/.codex/AGENTS.md, marker-block injection; skills in repo-local .agents/skills/
#   openclaw → ~/.openclaw/workspace/USER.md, marker-block injection
#
# --render-specs-only builds the in-repo context surface (scope specs, skills,
# optional-skills index, per-agent injection) and stops before any write outside
# the target dir — no shell-profile edits, no sibling clones, no git hooks, no
# connect marker. It lets a throwaway copy (a test sandbox, a CI checkout) be
# wired exactly like a real checkout with zero global side effects; codex/openclaw
# land in the copy when CODEX_HOME / OPENCLAW_WORKSPACE point there.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=skills-registry.sh
source "$SCRIPT_DIR/skills-registry.sh"

# --------------------------------------------------------------------------
# Linking helpers
# --------------------------------------------------------------------------

link_path() {
    local src="${1%/}" dst="$2" label="$3"
    [[ -e "$src" || -d "$src" ]] || return 0
    if [[ -L "$dst" ]]; then
        local existing; existing="$(readlink "$dst")"
        if [[ "${existing%/}" == "$src" ]]; then echo "  ✓ $label"; return; fi
        rm "$dst"
    elif [[ -e "$dst" ]]; then
        echo "  SKIP $label (real path exists, remove manually)"; return
    fi
    ln -s "$src" "$dst"
    echo "  + $label"
}

clean_stale() {
    local dir="$1"
    [[ -d "$dir" ]] || return 0
    find "$dir" -maxdepth 1 -type l ! -exec test -e {} \; -delete 2>/dev/null || true
}

# inject_block <file> <block_id> <content_file> <label>
inject_block() {
    local file="$1" block_id="$2" content_file="$3" label="$4"
    local begin="<!-- BEGIN $block_id -->" end="<!-- END $block_id -->"
    if [[ ! -f "$file" ]]; then
        { echo "$begin"; cat "$content_file"; echo "$end"; } > "$file"
        echo "  + $label (created)"
    elif grep -qF "$begin" "$file" && grep -qF "$end" "$file"; then
        awk -v begin="$begin" -v end="$end" -v cfile="$content_file" '
            $0 == begin { print; while ((getline line < cfile) > 0) print line; skip=1; next }
            $0 == end   { skip=0; print; next }
            !skip { print }
        ' "$file" > "${file}.tmp" && mv "${file}.tmp" "$file"
        echo "  ✓ $label (updated)"
    else
        { echo ""; echo "$begin"; cat "$content_file"; echo "$end"; } >> "$file"
        echo "  + $label (block appended)"
    fi
}

install_hook() {
    echo ""; echo "Installing git hooks..."
    local hooks_dir hook_tmp
    hooks_dir="$(git -C "$REPO_DIR" rev-parse --git-common-dir)/hooks"
    mkdir -p "$hooks_dir"

    # Re-link after pulling new commits. `post-merge` fires on `git pull`
    # (fast-forward and merge); `post-rewrite` fires on `git pull --rebase`
    # (guarded to skip plain `commit --amend`). Both keep the agent surface fresh.
    hook_tmp="$hooks_dir/post-merge.tmp.$$"
    cat > "$hook_tmp" << 'HOOK'
#!/usr/bin/env bash
# Auto-generated by connect-agent.sh — re-links exobrain after a merge/pull.
REPO_DIR="$(git rev-parse --show-toplevel)"
for a in claude codex openclaw; do
    "$REPO_DIR/scripts/connect-agent.sh" "$a" --relink 2>/dev/null || true
done
HOOK
    chmod +x "$hook_tmp"; mv -f "$hook_tmp" "$hooks_dir/post-merge"
    echo "  ✓ $hooks_dir/post-merge"

    hook_tmp="$hooks_dir/post-rewrite.tmp.$$"
    cat > "$hook_tmp" << 'HOOK'
#!/usr/bin/env bash
# Auto-generated by connect-agent.sh — re-links after a rebase-based pull.
[[ "$1" == "rebase" ]] || exit 0   # ignore commit --amend
REPO_DIR="$(git rev-parse --show-toplevel)"
for a in claude codex openclaw; do
    "$REPO_DIR/scripts/connect-agent.sh" "$a" --relink 2>/dev/null || true
done
HOOK
    chmod +x "$hook_tmp"; mv -f "$hook_tmp" "$hooks_dir/post-rewrite"
    echo "  ✓ $hooks_dir/post-rewrite"

    hook_tmp="$hooks_dir/pre-push.tmp.$$"
    cat > "$hook_tmp" << 'HOOK'
#!/usr/bin/env bash
# Auto-generated by connect-agent.sh — validates exobrain conventions before push.
REPO_DIR="$(git rev-parse --show-toplevel)"
if [[ -x "$REPO_DIR/scripts/validate-exobrain.sh" ]]; then
    "$REPO_DIR/scripts/validate-exobrain.sh" || {
        echo "Push blocked by exobrain validation. Fix the above, or 'git push --no-verify'." >&2
        exit 1
    }
fi
HOOK
    chmod +x "$hook_tmp"; mv -f "$hook_tmp" "$hooks_dir/pre-push"
    echo "  ✓ $hooks_dir/pre-push"
}

is_interactive() { [[ -t 0 && -t 1 ]]; }

# --------------------------------------------------------------------------
# Config + wizard
# --------------------------------------------------------------------------

CONFIG="$REPO_DIR/.exobrain.json"
CONNECTED_LEAVES=()
PERSON_ID=""   # the connecting user's person id; persisted as .person for owner-match

load_config() {
    [[ -f "$CONFIG" ]] || return 1
    local arr
    arr="$(jq -r '(.connected_scopes // []) | .[]' "$CONFIG" 2>/dev/null)" || return 1
    CONNECTED_LEAVES=()
    while IFS= read -r l; do [[ -n "$l" ]] && CONNECTED_LEAVES+=("$l"); done <<< "$arr"
    return 0
}

# save_config — write connected_scopes[] + agents[] + person, preserving any other
# keys (e.g. a tools block owned by a setup skill). `person` is written only when
# PERSON_ID is set, so a guest/host-only connection leaves it absent.
save_config() {
    local leaves_json agents_json existing="{}"
    [[ -f "$CONFIG" ]] && existing="$(cat "$CONFIG")"
    leaves_json="$(printf '%s\n' "${CONNECTED_LEAVES[@]}" | jq -R . | jq -s .)"
    agents_json="$(jq -r '(.agents // [])' <<< "$existing" 2>/dev/null || echo '[]')"
    agents_json="$(jq --arg a "$AGENT" '. as $cur | ($cur + [$a]) | unique' <<< "$agents_json")"
    jq -n --argjson e "$existing" --argjson c "$leaves_json" --argjson ag "$agents_json" --arg p "$PERSON_ID" \
        '$e + {connected_scopes: $c, agents: $ag} + (if $p == "" then {} else {person: $p} end)' \
        > "${CONFIG}.tmp" && mv "${CONFIG}.tmp" "$CONFIG"
    echo "  ✓ $CONFIG"
}

# scaffold_scope <path> <type-label> — create a scope dir with a stub AGENTS.md.
scaffold_scope() {
    local path="$1" label="$2"
    local dir="$REPO_DIR/$path"
    mkdir -p "$dir"
    if [[ ! -f "$dir/AGENTS.md" ]]; then
        local id="${path##*/}"
        printf '# %s — %s scope\n\nAgent context specific to this %s.\n' "$id" "$label" "$label" \
            > "$dir/AGENTS.md"
        echo "  + $path/AGENTS.md ($label scope)"
    fi
}

# discover_person_dirs <repo_dir> <handle> — print the repo-relative path of every
# existing person scope dir for <handle>, anywhere in the tree: top-level
# <people>/<handle> or nested <…>/<people>/<handle>. The person collection name
# comes from scopes.json vocabulary. Reads only; shared by the interactive wizard
# and the non-interactive auto-detect path.
discover_person_dirs() {
    local repo_dir="$1" handle="$2" person_coll
    person_coll="$(scopes_collection_for_type "$repo_dir" person)"
    find "$repo_dir" \
        \( -path '*/.git' -o -path '*/node_modules' -o -path '*/tmp' \
           -o -path '*/src' -o -path '*/.src' \) -prune -o \
        -type d -path "*/$person_coll/$handle" -print 2>/dev/null \
        | sed "s#^$repo_dir/##" | sort
}

# sanitize_id <raw> — lowercase, restrict to [a-z0-9._-] for a scope leaf id.
sanitize_id() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/-/g'; }

# run_wizard — derive the connectable leaf from the scope tree plus your choice.
# Person and host are "pinpoint" scopes (their leaf ids are your handle and this
# machine's hostname), so they place automatically. Interactive: confirm handle +
# host, then choose where the person scope lives — an existing one discovered in
# the tree, a new one under a group/team, or a new top-level person. Non-interactive:
# auto-connect the host leaf under every existing person scope for the handle,
# writing nothing (guest if none). Shapes come from scopes.json vocabulary, not a
# hardcoded people/…/hosts/… path; the scope resolver is left untouched.
run_wizard() {
    echo ""
    echo "First-time setup for this exobrain."

    local default_id default_host id host person_coll host_coll
    default_id="$(git -C "$REPO_DIR" config user.email 2>/dev/null | sed 's/@.*//' || true)"
    [[ -z "$default_id" ]] && default_id="${USER:-me}"
    default_host="$(hostname -s 2>/dev/null || echo localhost)"
    person_coll="$(scopes_collection_for_type "$REPO_DIR" person)"
    host_coll="$(scopes_collection_for_type "$REPO_DIR" host)"

    # Non-interactive: discover and connect, never write.
    if ! is_interactive; then
        id="$(sanitize_id "$default_id")"; host="$(sanitize_id "$default_host")"
        CONNECTED_LEAVES=()
        local p
        while IFS= read -r p; do
            [[ -n "$p" ]] && CONNECTED_LEAVES+=("$p/$host_coll/$host")
        done < <(discover_person_dirs "$REPO_DIR" "$id")
        if [[ ${#CONNECTED_LEAVES[@]} -eq 0 ]]; then
            echo "  Non-interactive, no person scope for '$id' — guest mode (global scope only)."
        else
            echo "  Non-interactive — auto-connected: ${CONNECTED_LEAVES[*]}"
        fi
        return 0
    fi

    printf 'Your handle (a short id for your person scope) [%s]: ' "$default_id" >/dev/tty
    read -r id </dev/tty; id="$(sanitize_id "${id:-$default_id}")"
    printf 'This machine name (host scope) [%s]: ' "$default_host" >/dev/tty
    read -r host </dev/tty; host="$(sanitize_id "${host:-$default_host}")"

    # Build the shape menu: existing person dirs for this handle, then a new person
    # under each existing container instance (group / team), then a new top-level person.
    local opt_paths=() opt_labels=() rel cc cdir cname ctype
    while IFS= read -r rel; do
        [[ -n "$rel" ]] || continue
        opt_paths+=("$rel"); opt_labels+=("Connect existing — $rel/")
    done < <(discover_person_dirs "$REPO_DIR" "$id")
    while IFS= read -r cc; do
        [[ -n "$cc" ]] || continue
        ctype="$(scope_type_for "$REPO_DIR" "$cc/_")"
        for cdir in "$REPO_DIR/$cc"/*/; do
            [[ -d "$cdir" ]] || continue
            cname="${cdir%/}"; cname="${cname##*/}"
            [[ -d "$REPO_DIR/$cc/$cname/$person_coll/$id" ]] && continue   # already listed above
            opt_paths+=("$cc/$cname/$person_coll/$id")
            opt_labels+=("New person under $ctype '$cname' — $cc/$cname/$person_coll/$id/")
        done
    done < <(scopes_container_collections "$REPO_DIR")
    if [[ ! -d "$REPO_DIR/$person_coll/$id" ]]; then
        opt_paths+=("$person_coll/$id"); opt_labels+=("New top-level person — $person_coll/$id/")
    fi

    local person_path
    if [[ ${#opt_paths[@]} -le 1 ]]; then
        person_path="${opt_paths[0]}"
    else
        echo "" >/dev/tty; echo "Where should your person scope live?" >/dev/tty
        local i
        for i in "${!opt_labels[@]}"; do printf '  %d. %s\n' "$((i + 1))" "${opt_labels[$i]}" >/dev/tty; done
        local choice
        printf 'Select [1]: ' >/dev/tty; read -r choice </dev/tty; choice="${choice:-1}"
        if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 1 && choice <= ${#opt_paths[@]} )); then
            person_path="${opt_paths[$((choice - 1))]}"
        else
            echo "  Invalid selection — using the first option." >/dev/tty
            person_path="${opt_paths[0]}"
        fi
    fi

    scaffold_scope "$person_path" person
    scaffold_scope "$person_path/$host_coll/$host" host
    CONNECTED_LEAVES=("$person_path/$host_coll/$host")
    PERSON_ID="$id"
    save_config
}

# --------------------------------------------------------------------------
# Argument parsing + agent setup
# --------------------------------------------------------------------------

AGENT="" ; RELINK=false ; CONFIGURE=false ; RENDER_ONLY=false
for arg in "$@"; do
    case "$arg" in
        claude|codex|openclaw) AGENT="$arg" ;;
        --relink)             RELINK=true ;;
        --configure)          CONFIGURE=true ;;
        --render-specs-only)  RENDER_ONLY=true ;;
        *) echo "Usage: $0 <claude|codex|openclaw> [--relink] [--configure] [--render-specs-only]" >&2; exit 2 ;;
    esac
done
[[ -n "$AGENT" ]] || { echo "Usage: $0 <claude|codex|openclaw> [--relink] [--configure] [--render-specs-only]" >&2; exit 2; }

# Hard dependency: jq drives config persistence and skills resolution. Fail
# early with an install hint rather than deep inside the run with a cryptic error.
if ! command -v jq >/dev/null 2>&1; then
    echo "Error: jq is required but not installed." >&2
    case "$(uname -s)" in
        Darwin) echo "  Install with: brew install jq" >&2 ;;
        Linux)  echo "  Install with: apt-get install jq  (or your distro's package manager)" >&2 ;;
    esac
    exit 1
fi

case "$AGENT" in
    claude)   MARKER="$REPO_DIR/.claude";   MARKER_IS_DIR=true;  TARGET_DIR="$REPO_DIR/.claude"
              AGENT_SIDECAR="CLAUDE.md";   AGENT_SIDECAR_BASE="CLAUDE" ;;
    codex)    MARKER="$REPO_DIR/.codex";    MARKER_IS_DIR=false; TARGET_DIR="${CODEX_HOME:-$HOME/.codex}"
              AGENT_SIDECAR="CODEX.md";    AGENT_SIDECAR_BASE="CODEX" ;;
    openclaw) MARKER="$REPO_DIR/.openclaw"; MARKER_IS_DIR=false; TARGET_DIR="${OPENCLAW_WORKSPACE:-$HOME/.openclaw/workspace}"
              AGENT_SIDECAR="OPENCLAW.md"; AGENT_SIDECAR_BASE="OPENCLAW" ;;
esac

# Where this agent's always-tier skills are linked. Most agents read skills from
# their context surface ($TARGET_DIR/skills). Codex is the exception: it scans a
# repo-local .agents/skills (cwd→repo-root), so its skills go there — keeping them
# out of the global ~/.codex config, scoped to this repo. SKILLS_OPTIONAL_DIR is the
# sibling the external-skill fetcher derives the same way.
case "$AGENT" in
    codex) SKILLS_DIR="$REPO_DIR/.agents/skills" ;;
    *)     SKILLS_DIR="$TARGET_DIR/skills" ;;
esac
SKILLS_OPTIONAL_DIR="$(dirname "$SKILLS_DIR")/skills-optional"

# On --relink, do nothing unless this agent has a marker (the user connected it).
if $RELINK; then
    if $MARKER_IS_DIR; then [[ -d "$MARKER" ]] || exit 0; else [[ -e "$MARKER" ]] || exit 0; fi
fi

# --------------------------------------------------------------------------
# Resolve config
# --------------------------------------------------------------------------

if $CONFIGURE || ! load_config; then
    # --render-specs-only never prompts or writes config: a copy with no config
    # renders as guest (global scope only), like --relink.
    if $CONFIGURE || { ! $RELINK && ! $RENDER_ONLY; }; then
        run_wizard
    else
        CONNECTED_LEAVES=()
    fi
fi

GUEST_MODE=false
[[ ${#CONNECTED_LEAVES[@]} -eq 0 ]] && GUEST_MODE=true

# Warn on any connected leaf that isn't actually a scope (no AGENTS.md), but
# keep going — its AGENTS.md-bearing ancestors still wire in.
for leaf in "${CONNECTED_LEAVES[@]:-}"; do
    [[ -z "$leaf" ]] && continue
    [[ -f "$REPO_DIR/$leaf/AGENTS.md" ]] || echo "  ! connected leaf '$leaf' has no AGENTS.md (not a scope) — using its scope ancestors only"
done

echo "Agent:     $AGENT"
echo "Target:    $TARGET_DIR"
echo "Connected: ${CONNECTED_LEAVES[*]:-<guest: global only>}"

# Both are real directories (the skills parent must be real, not a symlink, for
# codex to scan it); skill children are symlinked in below.
mkdir -p "$TARGET_DIR" "$SKILLS_DIR"
clean_stale "$SKILLS_DIR"
# Specs reach each agent without per-scope symlinks now (claude: a manifest of
# @-imports in connected-scopes.md; codex/openclaw: the marker block). Remove any
# AGENTS.<suffix>.md or sidecar symlink an earlier connect (old scheme) left behind.
# Only symlinks are deleted, so the generated files below are never touched.
find "$TARGET_DIR" -maxdepth 1 \( -name "AGENTS.*.md" -o -name "${AGENT_SIDECAR_BASE}.*.md" \) \
    -type l -delete 2>/dev/null || true

# --------------------------------------------------------------------------
# Resolve the scope chain + skills registry
# --------------------------------------------------------------------------

CHAIN=()
while IFS= read -r s; do CHAIN+=("$s"); done < <(build_scope_chain "$REPO_DIR" "${CONNECTED_LEAVES[@]:-}")

RESOLVED_TSV="$(skills_resolve "$REPO_DIR" "$AGENT" "${CONNECTED_LEAVES[@]:-}")"
REGISTRY_ACTIVE=false
[[ -n "$RESOLVED_TSV" ]] && REGISTRY_ACTIVE=true

# --------------------------------------------------------------------------
# Link always-tier in-tree skills (direct from the resolved registry)
# --------------------------------------------------------------------------

echo ""; echo "Skills:"
linked_any=false
declare -A _EXPECT_SKILL=()
# Parse tab fields by hand: `IFS=$'\t' read` collapses consecutive tabs (tab is
# IFS whitespace), dropping the empty owner of a global-scope row and shifting tier.
while IFS= read -r _row; do
    [[ -n "$_row" ]] || continue
    name="${_row%%$'\t'*}";  _row="${_row#*$'\t'}"
    scope="${_row%%$'\t'*}"; _row="${_row#*$'\t'}"
    owner="${_row%%$'\t'*}"; _row="${_row#*$'\t'}"
    tier="${_row%%$'\t'*}"
    [[ "$tier" == "always" ]] || continue
    [[ "$scope" == "external" ]] && continue   # external skills handled by the fetcher
    src="$(skills_dir_for "$REPO_DIR" "$scope" "$owner" "$name")"
    [[ -n "$src" && -d "$src" ]] || continue
    suffix="$(skills_link_suffix "$scope" "$owner")"
    dst="$SKILLS_DIR/${name}${suffix:+.$suffix}"
    link_path "$src" "$dst" "skills/${name}${suffix:+.$suffix}"
    _EXPECT_SKILL["${name}${suffix:+.$suffix}"]=1
    linked_any=true
done <<< "$RESOLVED_TSV"
$linked_any || echo "  (no always-tier skills)"

# --------------------------------------------------------------------------
# External skills (fetched third-party) — only when the registry declares any
# --------------------------------------------------------------------------

if awk -F'\t' '$2=="external"{f=1} END{exit !f}' <<< "$RESOLVED_TSV" && [[ -x "$SCRIPT_DIR/fetch-external-skills.sh" ]]; then
    echo ""; echo "External skills:"
    LEAVES_CSV="$(IFS=','; echo "${CONNECTED_LEAVES[*]:-}")"
    "$SCRIPT_DIR/fetch-external-skills.sh" "$SKILLS_DIR" --agent "$AGENT" --leaves "$LEAVES_CSV" || \
        echo "  (fetch-external-skills.sh failed — non-fatal)"
fi

# Prune managed in-tree skill symlinks no longer expected — a removed/off skill,
# or a link from a previous suffix scheme. External skills are fetched as real
# directories, not symlinks, so this loop never touches them.
for d in "$SKILLS_DIR"/*; do
    [[ -L "$d" ]] || continue
    bn="$(basename "$d")"
    [[ -n "${_EXPECT_SKILL[$bn]:-}" ]] || { rm "$d"; echo "  - removed stale skill $bn"; }
done

# Legacy migration: codex skills used to link under ~/.codex/skills (global); they
# now live in the repo-local .agents/skills. Remove the old exobrain symlinks (only
# links pointing back into this repo) so a re-linked codex install keeps no stale
# global copies; anything else under there is left untouched.
if [[ "$AGENT" == codex && "$SKILLS_DIR" != "$TARGET_DIR/skills" && -d "$TARGET_DIR/skills" ]]; then
    for _l in "$TARGET_DIR"/skills/*; do
        [[ -L "$_l" ]] || continue
        [[ "$(readlink "$_l")" == "$REPO_DIR"/* ]] && { rm "$_l"; echo "  - removed legacy codex skill link $(basename "$_l")"; }
    done
    rmdir "$TARGET_DIR/skills" 2>/dev/null || true
fi

# --------------------------------------------------------------------------
# Optional-skills index
# --------------------------------------------------------------------------

echo ""; echo "Optional skills index:"
INDEX_FILE="$TARGET_DIR/optional-skills.md"
if $REGISTRY_ACTIVE; then
    {
        cat <<'HEADER'
# Optional skills

These skills are registered but **not auto-loaded** into the agent's context. To use one:

1. Read its `SKILL.md` from the path below.
2. Follow the instructions inline.

| Name | Path | Summary |
|------|------|---------|
HEADER
        while IFS= read -r _row; do
            [[ -n "$_row" ]] || continue
            name="${_row%%$'\t'*}";  _row="${_row#*$'\t'}"
            scope="${_row%%$'\t'*}"; _row="${_row#*$'\t'}"
            owner="${_row%%$'\t'*}"; _row="${_row#*$'\t'}"
            tier="${_row%%$'\t'*}"
            [[ "$tier" == "optional" ]] || continue
            if [[ "$scope" == "external" ]]; then
                src="$SKILLS_OPTIONAL_DIR/${name}.$(sanitize_suffix "$owner")"
                [[ -d "$src" ]] || continue
                local_path="$src"
            else
                src="$(skills_dir_for "$REPO_DIR" "$scope" "$owner" "$name")"
                [[ -z "$src" || ! -d "$src" ]] && continue
                local_path="${src#"$REPO_DIR"/}"
            fi
            summary=""
            [[ -f "$src/SKILL.md" ]] && summary="$(skills_extract_description "$src/SKILL.md")"
            summary="${summary//|/\\|}"
            printf '| %s | %s | %s |\n' "$name" "$local_path/SKILL.md" "$summary"
        done <<< "$RESOLVED_TSV" | sort
    } > "$INDEX_FILE"
    echo "  + $INDEX_FILE"
else
    [[ -f "$INDEX_FILE" ]] && rm "$INDEX_FILE"
    echo "  SKIP (no registry in any connected scope)"
fi

# --------------------------------------------------------------------------
# Tools index — a flat catalog of every tool doc visible across the chain
# --------------------------------------------------------------------------
# Unlike skills, tools carry no tiers/force/owner: a doc's presence at a scope
# lists it for everyone in that chain. Connection state (which tools this machine
# has set up) lives separately in .exobrain.json; the index is a pure catalog, so
# it stays a function of committed docs and regenerates on the same relink triggers.
echo ""; echo "Tools index:"
TOOLS_INDEX_FILE="$TARGET_DIR/tools-index.md"
TOOLS_TSV="$(tools_resolve "$REPO_DIR" "${CONNECTED_LEAVES[@]:-}")"
if [[ -n "$TOOLS_TSV" ]]; then
    {
        cat <<'HEADER'
# Tools

External systems this agent can read from or act on. Each row points at a self-contained tool doc — **read the doc before using the tool**; it carries the setup, credentials, exact commands, and failure modes. Reach for one whenever a task maps to its summary.

Everyone sees the full catalog; connecting a tool is a separate per-machine step (the `exobrain-tools` skill; connection state in `.exobrain.json`). If a task needs a tool that isn't set up here, propose connecting it.

| Tool | Doc | Summary |
|------|-----|---------|
HEADER
        while IFS= read -r _row; do
            [[ -n "$_row" ]] || continue
            name="${_row%%$'\t'*}"; path="${_row#*$'\t'}"
            summary="$(tools_extract_summary "$REPO_DIR/$path")"
            summary="${summary//|/\\|}"
            printf '| %s | %s | %s |\n' "$name" "$path" "$summary"
        done <<< "$TOOLS_TSV"
    } > "$TOOLS_INDEX_FILE"
    echo "  + $TOOLS_INDEX_FILE"
else
    [[ -f "$TOOLS_INDEX_FILE" ]] && rm "$TOOLS_INDEX_FILE"
    echo "  SKIP (no tool docs in any connected scope)"
fi

# --------------------------------------------------------------------------
# Per-agent injection of scope specs into the agent surface
# --------------------------------------------------------------------------
# compose_context emits the connected chain's deeper-scope specs — each scope's
# AGENTS.md plus this agent's sidecar, shallow→deep — followed by the optional-
# skills index and the tools index, as one stream. The global scope (root AGENTS.md
# + root sidecar) is auto-loaded by the agent and is deliberately omitted. Shared by
# all backends so the composition lives in one place; only the delivery below differs.
compose_context() {
    for scope in "${CHAIN[@]}"; do
        [[ "$scope" == "global" ]] && continue
        if [[ -f "$REPO_DIR/$scope/AGENTS.md" ]]; then
            echo "<!-- scope: $scope -->"; echo ""; cat "$REPO_DIR/$scope/AGENTS.md"; echo ""
        fi
        if [[ -f "$REPO_DIR/$scope/$AGENT_SIDECAR" ]]; then
            echo "<!-- scope: $scope — $AGENT -->"; echo ""; cat "$REPO_DIR/$scope/$AGENT_SIDECAR"; echo ""
        fi
    done
    if [[ -f "$INDEX_FILE" ]]; then
        echo "<!-- optional-skills index -->"; echo ""; cat "$INDEX_FILE"; echo ""
    fi
    if [[ -f "$TOOLS_INDEX_FILE" ]]; then
        echo "<!-- tools index -->"; echo ""; cat "$TOOLS_INDEX_FILE"; echo ""
    fi
}

# compose_scope_manifest emits one @-import line per deeper-scope spec (each scope's
# AGENTS.md plus this agent's sidecar, shallow→deep) — for an agent that resolves
# recursive @-imports (Claude). It references the committed source files by path
# rather than copying them, so scope edits show up live without a recompose. Paths
# are RELATIVE to the manifest's home (.claude/, one level under REPO_DIR) — relative
# not absolute so a copied checkout (test sandbox, worktree) still resolves them. The
# global scope (root AGENTS.md + root sidecar) loads via the checked-in root CLAUDE.md
# and is deliberately omitted, matching compose_context.
compose_scope_manifest() {
    echo "<!-- Auto-generated by connect-agent.sh — do not edit; regenerated on relink. -->"
    echo "<!-- @-import manifest of connected-scope specs (live source files, by reference). -->"
    echo ""
    # `if` blocks, not a trailing `[[ … ]] && echo`: a conditional that tests false
    # returns 1, which under `set -e` aborts at the `… > file` call site whenever the
    # last scope lacks a sidecar. An `if` whose test fails returns 0, so the function
    # always succeeds (matching compose_context's style).
    for scope in "${CHAIN[@]}"; do
        [[ "$scope" == "global" ]] && continue
        if [[ -f "$REPO_DIR/$scope/AGENTS.md" ]];      then echo "@../$scope/AGENTS.md"; fi
        if [[ -f "$REPO_DIR/$scope/$AGENT_SIDECAR" ]]; then echo "@../$scope/$AGENT_SIDECAR"; fi
    done
}

case "$AGENT" in
    claude)
        # Claude's own surface — never a file another agent also writes. Claude
        # resolves recursive @-imports, so reference the live source specs through a
        # manifest (no inlined copy: scope edits show up without a recompose) plus the
        # agent-filtered optional-skills index and the tools index. The generated
        # .claude/CLAUDE.md @-imports them; the root spec loads via the checked-in root
        # CLAUDE.md (@AGENTS.md), so global stays out of the manifest.
        echo ""; echo "Composing Claude context surface …"
        compose_scope_manifest > "$TARGET_DIR/connected-scopes.md"
        echo "  ✓ .claude/connected-scopes.md (manifest of source specs)"
        {
            echo "@connected-scopes.md"
            # `if`, not `&& printf`: when an index is absent the trailing conditional
            # would return 1 and trip `set -e` at the `} > file` redirection.
            if [[ -f "$INDEX_FILE" ]]; then echo "@optional-skills.md"; fi
            if [[ -f "$TOOLS_INDEX_FILE" ]]; then echo "@tools-index.md"; fi
        } > "$TARGET_DIR/CLAUDE.md"
        echo "  ✓ .claude/CLAUDE.md"
        # Supersedes the earlier single inlined file; drop one an old connect left behind.
        rm -f "$TARGET_DIR/AGENTS.override.md"

        # Disable Claude Code's auto-memory — this exobrain provides context via
        # AGENTS.md/CLAUDE.md, so the separate auto-memory layer just adds drift.
        # settings.local.json is gitignored (per-machine); merge to preserve other keys.
        settings="$TARGET_DIR/settings.local.json"
        if command -v jq >/dev/null 2>&1; then
            if [[ -f "$settings" ]]; then
                jq '.autoMemoryEnabled = false' "$settings" > "${settings}.tmp" && mv "${settings}.tmp" "$settings"
            else
                echo '{"autoMemoryEnabled": false}' | jq . > "$settings"
            fi
            echo "  ✓ settings.local.json (autoMemoryEnabled: false)"
        else
            echo "  SKIP settings.local.json (jq not installed)"
        fi
        ;;
    codex|openclaw)
        # Inline root sidecar + each deeper scope's AGENTS.md (+ sidecar) + index
        # into the agent's auto-loaded file, between markers.
        if [[ "$AGENT" == codex ]]; then DEST="$TARGET_DIR/AGENTS.md"; else DEST="$TARGET_DIR/USER.md"; fi
        echo ""; echo "Injecting agent context into $(basename "$DEST") …"
        # Same composition as claude, delivered by marker-block rewrite (no import
        # primitive). codex/openclaw auto-load the root AGENTS.md but not the root
        # sidecar, so it is prepended here ahead of the shared deeper-scope content.
        CONTENT_TMP="$(mktemp)"
        {
            echo "<!-- Auto-generated by connect-agent.sh — do not edit manually. -->"; echo ""
            if [[ -f "$REPO_DIR/$AGENT_SIDECAR" ]]; then
                echo "<!-- scope: root ($AGENT) -->"; echo ""; cat "$REPO_DIR/$AGENT_SIDECAR"; echo ""
            fi
            compose_context
        } > "$CONTENT_TMP"
        mkdir -p "$TARGET_DIR"
        inject_block "$DEST" "exobrain" "$CONTENT_TMP" "$(basename "$DEST")"
        rm -f "$CONTENT_TMP"

        # Disable Codex project memory (codex only) — exobrain supplies context via
        # AGENTS.md, so Codex's separate memory layer just adds drift. Written to the
        # user-level config.toml Codex always reads; safe and idempotent.
        if [[ "$AGENT" == codex ]]; then
            codex_cfg="$TARGET_DIR/config.toml"
            if grep -q 'use_memories' "$codex_cfg" 2>/dev/null; then
                echo "  ✓ config.toml already sets use_memories (left as-is)"
            elif grep -q '^\[memories\]' "$codex_cfg" 2>/dev/null; then
                echo "  ! $codex_cfg has a [memories] table without use_memories — add 'use_memories = false' to disable Codex memory"
            else
                { echo ""; echo "# Disable Codex project memory — exobrain supplies context via AGENTS.md."
                  echo "[memories]"; echo "use_memories = false"; } >> "$codex_cfg"
                echo "  ✓ Codex memory disabled in $codex_cfg"
            fi
        fi
        ;;
esac

# --render-specs-only stops here. Everything above writes only inside the target
# dir (the in-repo .claude surface, or a *_HOME-overridden copy dir for codex/
# openclaw); the connect marker and git hooks below are the first writes outside
# it. Truncating here — not forking a parallel render path — keeps the rendered
# surface identical to what a full connect produces.
if $RENDER_ONLY; then
    echo ""; echo "✓ Rendered $AGENT context surface (no out-of-dir writes)."
    exit 0
fi

# --------------------------------------------------------------------------
# Marker + hooks (first run only)
# --------------------------------------------------------------------------

if ! $RELINK; then
    if $MARKER_IS_DIR; then mkdir -p "$MARKER"; else touch "$MARKER"; fi
    install_hook
fi

echo ""; echo "✓ Connected $AGENT."
